#!/bin/bash
export GREEN='\033[0;32m'
export RED='\033[0;31m'
export NC='\033[0m' # No Color

apt update
apt install neofetch -y
printf "${RED}Neofetch Install Complete...${NC}"
apt install neovim -y
printf "${RED}Neovim Install Complete...${NC}"
apt install ncdu -y
printf "${RED}NCDU Install Complete...${NC}"

apt install docker.io -y
apt install iperf3 -y
apt install speedtest-cli -y
systemctl enable docker
systemctl start docker

printf "${RED}Docker Install Complete...${NC}"

docker run -d \
--name="portainer" \
--restart on-failure \
-p 9000:9000 \
-p 8000:8000 \
-v /var/run/docker.sock:/var/run/docker.sock \
-v portainer_data:/data \
portainer/portainer-ce:latest

printf "${RED}Portainer Install Complete...${NC}"

docker run -d \
--name="pihole" \
--restart on-failure \
-p 53:53/tcp \
-p 53:53/udp \
-p 67:67/udp \
-p 1010:80/tcp \
-p 4443:443/tcp \
-v /docker/pihole/config:/etc/pihole \
-v /docker/pihole/dns:/etc/dnsmasq.d \
pihole/pihole:latest

printf "${RED}Pihole Install Complete...${NC}"
echo "All installs complete"
